{{ if $.Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promyze
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  {{- if $.Values.ingress.className }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ $.Values.ingress.hostnames.promyze }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: app
                port:
                  number: 80
  {{- if $.Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $.Values.ingress.hostnames.app | quote }}
      {{- if hasKey .Values.ingress.tls.secrets "app" }}
      secretName: {{ $.Values.ingress.tls.secrets.app }}
      {{- end }}
  {{- end }}
{{ end }}
