{{ if $.Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: promyze
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
  {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.ingress.className }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ $.Values.ingress.hostnames.app }}
      http:
        paths:
          - pathType: Prefix
            path: "/api/plugin"
            backend:
              service:
                name: promyze-suggestions
                port:
                  number: 3000
          - pathType: Prefix
            path: "/api/suggestion"
            backend:
              service:
                name: promyze-suggestions
                port:
                  number: 3000
          - pathType: Prefix
            path: "/api"
            backend:
              service:
                name: promyze-api
                port:
                  number: 3000
          - pathType: Prefix
            path: "/open"
            backend:
              service:
                name: promyze-api
                port:
                  number: 3000
          - pathType: Prefix
            path: "/auth"
            backend:
              service:
                name: promyze-api
                port:
                  number: 3000
          - pathType: Prefix
            path: "/public"
            backend:
              service:
                name: promyze-api
                port:
                  number: 3000
          - pathType: Prefix
            path: "/techcoach"
            backend:
              service:
                name: promyze-suggestions
                port:
                  number: 3000
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: front
                port:
                  number: 80
  {{- if $.Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $.Values.ingress.hostnames.app | quote }}
      {{- if and .Values.ingress.tls.secrets .Values.ingress.tls.secrets.app }}
      secretName: {{ $.Values.ingress.tls.secrets.app }}
      {{- end }}
  {{- end }}
{{ end }}
