{{ if and .Values.app.images.secret .Values.app.images.secret.dockerconfigjson }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Values.app.images.secret.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.app.images.secret.dockerconfigjson | quote }}
{{ end }}
---