{{ if $.Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sso-ingress
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
  {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if $.Values.ingress.className }}
  ingressClassName: {{ $.Values.ingress.className }}
  {{- end }}
  rules:
    {{- range $value := .Values.ingress.hostnames }}
    - host: {{ $value | quote }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: cryptr-service
                port:
                  number: 4000
    {{- end }}
  {{- if $.Values.ingress.tls.enabled }}
  tls:
    - hosts:
        {{- range $value := .Values.ingress.hostnames }}
        - {{ $value | quote }}
        {{- end }}
      {{- if and .Values.ingress.tls.secrets .Values.ingress.tls.secrets.secretName }}
      secretName: {{ $.Values.ingress.tls.secrets.secretName }}
      {{- end }}
  {{- end }}
{{ end }}
