---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      component: app
  template:
    metadata:
      labels:
        component: app
    spec:
      containers:
        - name: app
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          livenessProbe:
           httpGet:
             path: /
             port: 3001
           initialDelaySeconds: 30
           periodSeconds: 30
          env:
            - name: MONGODB_URI
              {{ if .Values.app.databaseUri.value }}
              value: {{ .Values.app.databaseUri.value }}
              {{ end }}
              {{ if .Values.app.databaseUri.secret }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.databaseUri.secret.name }}
                  key: {{ .Values.app.databaseUri.secret.key }}
              {{ end }}
            - name: MONGODB_DB
              {{ if .Values.app.databaseUri.db }}
              value: {{ .Values.app.databaseUri.db }}
              {{ end }}
            {{- range $key, $value := .Values.app.variables }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- range $key, $value := .Values.app.secrets }}
            - name: {{ $value.envVariable }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.secretName }}
                  key: {{ $value.secretKey }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ if .Values.app.databaseEmbedded.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    component: mongodb
spec:
  selector:
    matchLabels:
      component: mongodb
  template:
    metadata:
      labels:
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.1
        ports:
          - containerPort: 27017
        {{ if .Values.app.databaseEmbedded.pvc.enabled }}
        volumeMounts:
        - name: mongo-data-dir
          mountPath: /data/db
        {{ end }}
      {{ if .Values.app.databaseEmbedded.pvc.enabled }}
      volumes:
      - name: mongo-data-dir
        persistentVolumeClaim:
          claimName: mongo-pvc
      {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{ end }}
