---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    component: app
  ports:
    - name: http
      port: 80
      targetPort: 3001
{{ if .Values.app.databaseEmbedded.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    component: mongodb
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
{{ end }}
