---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    component: app
  ports:
    - name: http
      port: 80
      targetPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    component: mongodb
  ports:
    - name: http
      port: 27017