apiVersion: v2
name: sso-cryptr
type: application
version: 1.0.0
appVersion: 1.0.0
description: Leverage SSO in Packmind
home: https://github.com/promyze/helm-charts
maintainers:
  - name: cteyton
    email: cedric.teyton@packmind.com
icon: https://packmind.com/wp-content/uploads/2024/01/LogoMark_Packmind.png
