name: Release

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Add dependency chart repositories
        run: ./scripts/add_helm_repo.sh
      - name: Set environment variables based on branch
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "DEPLOY_ENV=dev" >> $GITHUB_ENV
            echo "CR_SKIP_EXISTING=false" >> $GITHUB_ENV  # Override skip existing for dev
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
            echo "CR_SKIP_EXISTING=true" >> $GITHUB_ENV  # Keep CR_SKIP_EXISTING true for main
          fi
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: ${{ env.CR_SKIP_EXISTING }}
